version: "3"
services:
  validator:
    image: ankrnetwork/bas-template-bsc:devel
    command:
      - "geth"
      - "--datadir=/datadir"
      - "--genesis=/datadir/genesis.json"
      - "--mine"
      - "--password=/datadir/password.txt"
      - "--allow-insecure-unlock"
      - "--unlock=0xa6ff33e3250cc765052ac9d7f7dfebda183c4b9b"
      - "--miner.etherbase=0xa6ff33e3250cc765052ac9d7f7dfebda183c4b9b"
      - "--bootnodes=enode://5c8e90050fabb7e14e4921dc107caf533140112245e7a231d0edc49861cd779760ad4804e7034952a5cc79422fa9d31c54e9a6141fb4995af7a6bfce7a39140f@bootnode:30303"
      - "--gcmode=archive"
      - "--syncmode=full"
      - "--networkid=17243"
    volumes:
      - "../genesis.json:/datadir/genesis.json"
      - "../keystore:/datadir/keystore"
      - "../password.txt:/datadir/password.txt"
      - "./datadir/validator:/datadir/geth"
    restart: always

